TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += kicker.db
DB += kicker_power.db
DATA += kicker.proto

#=======================================
include $(TOP)/configure/RULES
