TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += kicker.db
DB += kicker_voltage.db
DB += kicker_current.db
DB += kicker_power.db

DATA += kicker.proto

#=======================================
include $(TOP)/configure/RULES
